-- ============================================
-- Invite Codes for Coach → Client Linking
-- ============================================

-- Table: invite codes generated by coaches
CREATE TABLE IF NOT EXISTS invite_codes (
  id          uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  coach_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  code        text NOT NULL UNIQUE,
  label       text,                          -- optional label e.g. "January batch"
  max_uses    int DEFAULT 1,                 -- how many clients can use this code
  used_count  int DEFAULT 0,
  expires_at  timestamptz,                   -- null = never expires
  created_at  timestamptz DEFAULT now(),
  active      boolean DEFAULT true
);

-- Indexes
CREATE INDEX idx_invite_codes_coach ON invite_codes(coach_id);
CREATE UNIQUE INDEX idx_invite_codes_code ON invite_codes(code);

-- RLS
ALTER TABLE invite_codes ENABLE ROW LEVEL SECURITY;

-- Coaches can manage their own codes
CREATE POLICY "Coaches manage own invite codes"
  ON invite_codes FOR ALL
  USING (coach_id = auth.uid())
  WITH CHECK (coach_id = auth.uid());

-- Anyone authenticated can read a code (to validate it during signup)
CREATE POLICY "Anyone can validate invite codes"
  ON invite_codes FOR SELECT
  USING (auth.role() = 'authenticated');

-- Ensure coach_clients table exists (may already exist)
CREATE TABLE IF NOT EXISTS coach_clients (
  id           uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  coach_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  client_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  goal         text DEFAULT 'maintenance',
  start_date   date DEFAULT CURRENT_DATE,
  program_week int DEFAULT 1,
  total_weeks  int DEFAULT 12,
  step_target  int DEFAULT 10000,
  workout_days text[] DEFAULT '{}',
  created_at   timestamptz DEFAULT now(),
  UNIQUE(coach_id, client_id)
);

-- RLS for coach_clients (if not already set)
ALTER TABLE coach_clients ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist (safe re-run)
DROP POLICY IF EXISTS "Coaches see own clients" ON coach_clients;
DROP POLICY IF EXISTS "Clients see own link" ON coach_clients;
DROP POLICY IF EXISTS "Insert coach_clients" ON coach_clients;

CREATE POLICY "Coaches see own clients"
  ON coach_clients FOR SELECT
  USING (coach_id = auth.uid());

CREATE POLICY "Clients see own link"
  ON coach_clients FOR SELECT
  USING (client_id = auth.uid());

-- Allow inserts (used when redeeming invite code)
CREATE POLICY "Insert coach_clients"
  ON coach_clients FOR INSERT
  WITH CHECK (
    coach_id = auth.uid() OR client_id = auth.uid()
  );

-- Allow coaches to update their client rows
DROP POLICY IF EXISTS "Coaches update own clients" ON coach_clients;
CREATE POLICY "Coaches update own clients"
  ON coach_clients FOR UPDATE
  USING (coach_id = auth.uid());
